package com.dwh.payweb.mapper;

import com.dwh.payweb.entity.Business;
import com.dwh.payweb.entity.BusinessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    long countByExample(BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    int deleteByExample(BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    int deleteByPrimaryKey(Integer businid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    int insert(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    int insertSelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    List<Business> selectByExample(BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    Business selectByPrimaryKey(Integer businid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") Business record, @Param("example") BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    int updateByExample(@Param("record") Business record, @Param("example") BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    int updateByPrimaryKeySelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    int updateByPrimaryKey(Business record);
}