package com.dwh.payweb.mapper;

import com.dwh.payweb.entity.Goods_pro;
import com.dwh.payweb.entity.Goods_proExample;
import com.dwh.payweb.entity.Goods_proKey;
import java.util.List;

import com.dwh.payweb.mapper.add.BaseGoods_pro;
import org.apache.ibatis.annotations.Param;

public interface Goods_proMapper extends BaseGoods_pro {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_goods_pro
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    long countByExample(Goods_proExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_goods_pro
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    int deleteByExample(Goods_proExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_goods_pro
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    int deleteByPrimaryKey(Goods_proKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_goods_pro
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    int insert(Goods_pro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_goods_pro
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    int insertSelective(Goods_pro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_goods_pro
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    List<Goods_pro> selectByExample(Goods_proExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_goods_pro
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    Goods_pro selectByPrimaryKey(Goods_proKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_goods_pro
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") Goods_pro record, @Param("example") Goods_proExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_goods_pro
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    int updateByExample(@Param("record") Goods_pro record, @Param("example") Goods_proExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_goods_pro
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    int updateByPrimaryKeySelective(Goods_pro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_goods_pro
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    int updateByPrimaryKey(Goods_pro record);
}