package com.dwh.payweb.mapper;

import com.dwh.payweb.Response.entity.PayResponse;
import com.dwh.payweb.entity.Pay;
import com.dwh.payweb.entity.PayExample;
import com.dwh.payweb.entity.PayKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    long countByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int deleteByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int deleteByPrimaryKey(PayKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int insert(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int insertSelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    List<Pay> selectByExample(PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    Pay selectByPrimaryKey(PayKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") Pay record, @Param("example") PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int updateByExample(@Param("record") Pay record, @Param("example") PayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int updateByPrimaryKeySelective(Pay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int updateByPrimaryKey(Pay record);

    List<PayResponse> selectAllPay();
}