package com.dwh.payweb.mapper;

import com.dwh.payweb.entity.Record;
import com.dwh.payweb.entity.RecordExample;
import com.dwh.payweb.entity.RecordKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_user_store
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    long countByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_user_store
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int deleteByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_user_store
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int deleteByPrimaryKey(RecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_user_store
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_user_store
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int insertSelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_user_store
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    List<Record> selectByExample(RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_user_store
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    Record selectByPrimaryKey(RecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_user_store
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") Record record, @Param("example") RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_user_store
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int updateByExample(@Param("record") Record record, @Param("example") RecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_user_store
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int updateByPrimaryKeySelective(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_user_store
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    int updateByPrimaryKey(Record record);
}