package com.dwh.payweb.mapper;

import com.dwh.payweb.entity.Trade;
import com.dwh.payweb.entity.TradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_trade
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    long countByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_trade
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    int deleteByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_trade
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    int deleteByPrimaryKey(String tradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_trade
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    int insert(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_trade
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    int insertSelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_trade
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    List<Trade> selectByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_trade
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    Trade selectByPrimaryKey(String tradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_trade
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") Trade record, @Param("example") TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_trade
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    int updateByExample(@Param("record") Trade record, @Param("example") TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_trade
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    int updateByPrimaryKeySelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_trade
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    int updateByPrimaryKey(Trade record);
}