package com.dwh.mapper;

import com.dwh.entity.InvalidCommpara;
import com.dwh.entity.InvalidCommparaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvalidCommparaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    int countByExample(InvalidCommparaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    int deleteByExample(InvalidCommparaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    int deleteByPrimaryKey(String paraCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    int insert(InvalidCommpara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    int insertSelective(InvalidCommpara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    List<InvalidCommpara> selectByExample(InvalidCommparaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    InvalidCommpara selectByPrimaryKey(String paraCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") InvalidCommpara record, @Param("example") InvalidCommparaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    int updateByExample(@Param("record") InvalidCommpara record, @Param("example") InvalidCommparaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    int updateByPrimaryKeySelective(InvalidCommpara record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    int updateByPrimaryKey(InvalidCommpara record);
}