package com.dwh.payweb.entity;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_goods.Gid
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    private String gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_goods.Gname
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_goods.UseDate
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    private Date usedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_goods.price
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_goods.version
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_goods.Time
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_goods.Gid
     *
     * @return the value of dwh_goods.Gid
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_goods.Gid
     *
     * @param gid the value for dwh_goods.Gid
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_goods.Gname
     *
     * @return the value of dwh_goods.Gname
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_goods.Gname
     *
     * @param gname the value for dwh_goods.Gname
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_goods.UseDate
     *
     * @return the value of dwh_goods.UseDate
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public Date getUsedate() {
        return usedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_goods.UseDate
     *
     * @param usedate the value for dwh_goods.UseDate
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public void setUsedate(Date usedate) {
        this.usedate = usedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_goods.price
     *
     * @return the value of dwh_goods.price
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_goods.price
     *
     * @param price the value for dwh_goods.price
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_goods.version
     *
     * @return the value of dwh_goods.version
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_goods.version
     *
     * @param version the value for dwh_goods.version
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_goods.Time
     *
     * @return the value of dwh_goods.Time
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_goods.Time
     *
     * @param time the value for dwh_goods.Time
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}