package com.dwh.payweb.entity;

public class Goods_pro extends Goods_proKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_goods_pro.p_number
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    private String pNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_goods_pro.p_area
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    private Integer pArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_goods_pro.m_area
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    private Integer mArea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_goods_pro.p_number
     *
     * @return the value of dwh_goods_pro.p_number
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public String getpNumber() {
        return pNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_goods_pro.p_number
     *
     * @param pNumber the value for dwh_goods_pro.p_number
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public void setpNumber(String pNumber) {
        this.pNumber = pNumber == null ? null : pNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_goods_pro.p_area
     *
     * @return the value of dwh_goods_pro.p_area
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public Integer getpArea() {
        return pArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_goods_pro.p_area
     *
     * @param pArea the value for dwh_goods_pro.p_area
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public void setpArea(Integer pArea) {
        this.pArea = pArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_goods_pro.m_area
     *
     * @return the value of dwh_goods_pro.m_area
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public Integer getmArea() {
        return mArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_goods_pro.m_area
     *
     * @param mArea the value for dwh_goods_pro.m_area
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public void setmArea(Integer mArea) {
        this.mArea = mArea;
    }
}