package com.dwh.payweb.entity;

public class Pay extends PayKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_pay.Pay_Date
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private String payDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_pay.Goodslist
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private String goodslist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_pay.Numlist
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private String numlist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_pay.Price
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_pay.Pricelist
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private String pricelist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_pay.Pay_Date
     *
     * @return the value of dwh_pay.Pay_Date
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public String getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_pay.Pay_Date
     *
     * @param payDate the value for dwh_pay.Pay_Date
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setPayDate(String payDate) {
        this.payDate = payDate == null ? null : payDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_pay.Goodslist
     *
     * @return the value of dwh_pay.Goodslist
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public String getGoodslist() {
        return goodslist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_pay.Goodslist
     *
     * @param goodslist the value for dwh_pay.Goodslist
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setGoodslist(String goodslist) {
        this.goodslist = goodslist == null ? null : goodslist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_pay.Numlist
     *
     * @return the value of dwh_pay.Numlist
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public String getNumlist() {
        return numlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_pay.Numlist
     *
     * @param numlist the value for dwh_pay.Numlist
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setNumlist(String numlist) {
        this.numlist = numlist == null ? null : numlist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_pay.Price
     *
     * @return the value of dwh_pay.Price
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_pay.Price
     *
     * @param price the value for dwh_pay.Price
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_pay.Pricelist
     *
     * @return the value of dwh_pay.Pricelist
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public String getPricelist() {
        return pricelist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_pay.Pricelist
     *
     * @param pricelist the value for dwh_pay.Pricelist
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setPricelist(String pricelist) {
        this.pricelist = pricelist == null ? null : pricelist.trim();
    }
}