package com.dwh.payweb.entity;

import java.util.ArrayList;
import java.util.List;

public class PayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public PayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUseridIsNull() {
            addCriterion("UserId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("UserId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("UserId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("UserId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("UserId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("UserId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("UserId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("UserId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("UserId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("UserId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("UserId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("UserId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andStoreidIsNull() {
            addCriterion("StoreId is null");
            return (Criteria) this;
        }

        public Criteria andStoreidIsNotNull() {
            addCriterion("StoreId is not null");
            return (Criteria) this;
        }

        public Criteria andStoreidEqualTo(Integer value) {
            addCriterion("StoreId =", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotEqualTo(Integer value) {
            addCriterion("StoreId <>", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThan(Integer value) {
            addCriterion("StoreId >", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThanOrEqualTo(Integer value) {
            addCriterion("StoreId >=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThan(Integer value) {
            addCriterion("StoreId <", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThanOrEqualTo(Integer value) {
            addCriterion("StoreId <=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidIn(List<Integer> values) {
            addCriterion("StoreId in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotIn(List<Integer> values) {
            addCriterion("StoreId not in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidBetween(Integer value1, Integer value2) {
            addCriterion("StoreId between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotBetween(Integer value1, Integer value2) {
            addCriterion("StoreId not between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andBusinidIsNull() {
            addCriterion("BusinId is null");
            return (Criteria) this;
        }

        public Criteria andBusinidIsNotNull() {
            addCriterion("BusinId is not null");
            return (Criteria) this;
        }

        public Criteria andBusinidEqualTo(Integer value) {
            addCriterion("BusinId =", value, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidNotEqualTo(Integer value) {
            addCriterion("BusinId <>", value, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidGreaterThan(Integer value) {
            addCriterion("BusinId >", value, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidGreaterThanOrEqualTo(Integer value) {
            addCriterion("BusinId >=", value, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidLessThan(Integer value) {
            addCriterion("BusinId <", value, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidLessThanOrEqualTo(Integer value) {
            addCriterion("BusinId <=", value, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidIn(List<Integer> values) {
            addCriterion("BusinId in", values, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidNotIn(List<Integer> values) {
            addCriterion("BusinId not in", values, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidBetween(Integer value1, Integer value2) {
            addCriterion("BusinId between", value1, value2, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidNotBetween(Integer value1, Integer value2) {
            addCriterion("BusinId not between", value1, value2, "businid");
            return (Criteria) this;
        }

        public Criteria andPayidIsNull() {
            addCriterion("PayId is null");
            return (Criteria) this;
        }

        public Criteria andPayidIsNotNull() {
            addCriterion("PayId is not null");
            return (Criteria) this;
        }

        public Criteria andPayidEqualTo(String value) {
            addCriterion("PayId =", value, "payid");
            return (Criteria) this;
        }

        public Criteria andPayidNotEqualTo(String value) {
            addCriterion("PayId <>", value, "payid");
            return (Criteria) this;
        }

        public Criteria andPayidGreaterThan(String value) {
            addCriterion("PayId >", value, "payid");
            return (Criteria) this;
        }

        public Criteria andPayidGreaterThanOrEqualTo(String value) {
            addCriterion("PayId >=", value, "payid");
            return (Criteria) this;
        }

        public Criteria andPayidLessThan(String value) {
            addCriterion("PayId <", value, "payid");
            return (Criteria) this;
        }

        public Criteria andPayidLessThanOrEqualTo(String value) {
            addCriterion("PayId <=", value, "payid");
            return (Criteria) this;
        }

        public Criteria andPayidLike(String value) {
            addCriterion("PayId like", value, "payid");
            return (Criteria) this;
        }

        public Criteria andPayidNotLike(String value) {
            addCriterion("PayId not like", value, "payid");
            return (Criteria) this;
        }

        public Criteria andPayidIn(List<String> values) {
            addCriterion("PayId in", values, "payid");
            return (Criteria) this;
        }

        public Criteria andPayidNotIn(List<String> values) {
            addCriterion("PayId not in", values, "payid");
            return (Criteria) this;
        }

        public Criteria andPayidBetween(String value1, String value2) {
            addCriterion("PayId between", value1, value2, "payid");
            return (Criteria) this;
        }

        public Criteria andPayidNotBetween(String value1, String value2) {
            addCriterion("PayId not between", value1, value2, "payid");
            return (Criteria) this;
        }

        public Criteria andPayDateIsNull() {
            addCriterion("Pay_Date is null");
            return (Criteria) this;
        }

        public Criteria andPayDateIsNotNull() {
            addCriterion("Pay_Date is not null");
            return (Criteria) this;
        }

        public Criteria andPayDateEqualTo(String value) {
            addCriterion("Pay_Date =", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateNotEqualTo(String value) {
            addCriterion("Pay_Date <>", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateGreaterThan(String value) {
            addCriterion("Pay_Date >", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateGreaterThanOrEqualTo(String value) {
            addCriterion("Pay_Date >=", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateLessThan(String value) {
            addCriterion("Pay_Date <", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateLessThanOrEqualTo(String value) {
            addCriterion("Pay_Date <=", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateLike(String value) {
            addCriterion("Pay_Date like", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateNotLike(String value) {
            addCriterion("Pay_Date not like", value, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateIn(List<String> values) {
            addCriterion("Pay_Date in", values, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateNotIn(List<String> values) {
            addCriterion("Pay_Date not in", values, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateBetween(String value1, String value2) {
            addCriterion("Pay_Date between", value1, value2, "payDate");
            return (Criteria) this;
        }

        public Criteria andPayDateNotBetween(String value1, String value2) {
            addCriterion("Pay_Date not between", value1, value2, "payDate");
            return (Criteria) this;
        }

        public Criteria andGoodslistIsNull() {
            addCriterion("Goodslist is null");
            return (Criteria) this;
        }

        public Criteria andGoodslistIsNotNull() {
            addCriterion("Goodslist is not null");
            return (Criteria) this;
        }

        public Criteria andGoodslistEqualTo(String value) {
            addCriterion("Goodslist =", value, "goodslist");
            return (Criteria) this;
        }

        public Criteria andGoodslistNotEqualTo(String value) {
            addCriterion("Goodslist <>", value, "goodslist");
            return (Criteria) this;
        }

        public Criteria andGoodslistGreaterThan(String value) {
            addCriterion("Goodslist >", value, "goodslist");
            return (Criteria) this;
        }

        public Criteria andGoodslistGreaterThanOrEqualTo(String value) {
            addCriterion("Goodslist >=", value, "goodslist");
            return (Criteria) this;
        }

        public Criteria andGoodslistLessThan(String value) {
            addCriterion("Goodslist <", value, "goodslist");
            return (Criteria) this;
        }

        public Criteria andGoodslistLessThanOrEqualTo(String value) {
            addCriterion("Goodslist <=", value, "goodslist");
            return (Criteria) this;
        }

        public Criteria andGoodslistLike(String value) {
            addCriterion("Goodslist like", value, "goodslist");
            return (Criteria) this;
        }

        public Criteria andGoodslistNotLike(String value) {
            addCriterion("Goodslist not like", value, "goodslist");
            return (Criteria) this;
        }

        public Criteria andGoodslistIn(List<String> values) {
            addCriterion("Goodslist in", values, "goodslist");
            return (Criteria) this;
        }

        public Criteria andGoodslistNotIn(List<String> values) {
            addCriterion("Goodslist not in", values, "goodslist");
            return (Criteria) this;
        }

        public Criteria andGoodslistBetween(String value1, String value2) {
            addCriterion("Goodslist between", value1, value2, "goodslist");
            return (Criteria) this;
        }

        public Criteria andGoodslistNotBetween(String value1, String value2) {
            addCriterion("Goodslist not between", value1, value2, "goodslist");
            return (Criteria) this;
        }

        public Criteria andNumlistIsNull() {
            addCriterion("Numlist is null");
            return (Criteria) this;
        }

        public Criteria andNumlistIsNotNull() {
            addCriterion("Numlist is not null");
            return (Criteria) this;
        }

        public Criteria andNumlistEqualTo(String value) {
            addCriterion("Numlist =", value, "numlist");
            return (Criteria) this;
        }

        public Criteria andNumlistNotEqualTo(String value) {
            addCriterion("Numlist <>", value, "numlist");
            return (Criteria) this;
        }

        public Criteria andNumlistGreaterThan(String value) {
            addCriterion("Numlist >", value, "numlist");
            return (Criteria) this;
        }

        public Criteria andNumlistGreaterThanOrEqualTo(String value) {
            addCriterion("Numlist >=", value, "numlist");
            return (Criteria) this;
        }

        public Criteria andNumlistLessThan(String value) {
            addCriterion("Numlist <", value, "numlist");
            return (Criteria) this;
        }

        public Criteria andNumlistLessThanOrEqualTo(String value) {
            addCriterion("Numlist <=", value, "numlist");
            return (Criteria) this;
        }

        public Criteria andNumlistLike(String value) {
            addCriterion("Numlist like", value, "numlist");
            return (Criteria) this;
        }

        public Criteria andNumlistNotLike(String value) {
            addCriterion("Numlist not like", value, "numlist");
            return (Criteria) this;
        }

        public Criteria andNumlistIn(List<String> values) {
            addCriterion("Numlist in", values, "numlist");
            return (Criteria) this;
        }

        public Criteria andNumlistNotIn(List<String> values) {
            addCriterion("Numlist not in", values, "numlist");
            return (Criteria) this;
        }

        public Criteria andNumlistBetween(String value1, String value2) {
            addCriterion("Numlist between", value1, value2, "numlist");
            return (Criteria) this;
        }

        public Criteria andNumlistNotBetween(String value1, String value2) {
            addCriterion("Numlist not between", value1, value2, "numlist");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("Price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("Price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("Price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("Price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("Price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("Price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("Price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("Price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("Price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("Price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("Price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("Price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPricelistIsNull() {
            addCriterion("Pricelist is null");
            return (Criteria) this;
        }

        public Criteria andPricelistIsNotNull() {
            addCriterion("Pricelist is not null");
            return (Criteria) this;
        }

        public Criteria andPricelistEqualTo(String value) {
            addCriterion("Pricelist =", value, "pricelist");
            return (Criteria) this;
        }

        public Criteria andPricelistNotEqualTo(String value) {
            addCriterion("Pricelist <>", value, "pricelist");
            return (Criteria) this;
        }

        public Criteria andPricelistGreaterThan(String value) {
            addCriterion("Pricelist >", value, "pricelist");
            return (Criteria) this;
        }

        public Criteria andPricelistGreaterThanOrEqualTo(String value) {
            addCriterion("Pricelist >=", value, "pricelist");
            return (Criteria) this;
        }

        public Criteria andPricelistLessThan(String value) {
            addCriterion("Pricelist <", value, "pricelist");
            return (Criteria) this;
        }

        public Criteria andPricelistLessThanOrEqualTo(String value) {
            addCriterion("Pricelist <=", value, "pricelist");
            return (Criteria) this;
        }

        public Criteria andPricelistLike(String value) {
            addCriterion("Pricelist like", value, "pricelist");
            return (Criteria) this;
        }

        public Criteria andPricelistNotLike(String value) {
            addCriterion("Pricelist not like", value, "pricelist");
            return (Criteria) this;
        }

        public Criteria andPricelistIn(List<String> values) {
            addCriterion("Pricelist in", values, "pricelist");
            return (Criteria) this;
        }

        public Criteria andPricelistNotIn(List<String> values) {
            addCriterion("Pricelist not in", values, "pricelist");
            return (Criteria) this;
        }

        public Criteria andPricelistBetween(String value1, String value2) {
            addCriterion("Pricelist between", value1, value2, "pricelist");
            return (Criteria) this;
        }

        public Criteria andPricelistNotBetween(String value1, String value2) {
            addCriterion("Pricelist not between", value1, value2, "pricelist");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dwh_pay
     *
     * @mbg.generated do_not_delete_during_merge Fri May 22 18:32:04 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dwh_pay
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}