package com.dwh.payweb.entity;

public class PayKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_pay.UserId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_pay.StoreId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private Integer storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_pay.BusinId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private Integer businid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_pay.PayId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private String payid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_pay.UserId
     *
     * @return the value of dwh_pay.UserId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_pay.UserId
     *
     * @param userid the value for dwh_pay.UserId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_pay.StoreId
     *
     * @return the value of dwh_pay.StoreId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_pay.StoreId
     *
     * @param storeid the value for dwh_pay.StoreId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_pay.BusinId
     *
     * @return the value of dwh_pay.BusinId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public Integer getBusinid() {
        return businid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_pay.BusinId
     *
     * @param businid the value for dwh_pay.BusinId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setBusinid(Integer businid) {
        this.businid = businid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_pay.PayId
     *
     * @return the value of dwh_pay.PayId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public String getPayid() {
        return payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_pay.PayId
     *
     * @param payid the value for dwh_pay.PayId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setPayid(String payid) {
        this.payid = payid == null ? null : payid.trim();
    }
}