package com.dwh.payweb.entity;

public class Record extends RecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_user_store.BusinId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private Integer businid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_user_store.Pay_Date
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private String payDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_user_store.statis
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private Integer statis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_user_store.BusinId
     *
     * @return the value of dwh_user_store.BusinId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public Integer getBusinid() {
        return businid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_user_store.BusinId
     *
     * @param businid the value for dwh_user_store.BusinId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setBusinid(Integer businid) {
        this.businid = businid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_user_store.Pay_Date
     *
     * @return the value of dwh_user_store.Pay_Date
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public String getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_user_store.Pay_Date
     *
     * @param payDate the value for dwh_user_store.Pay_Date
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setPayDate(String payDate) {
        this.payDate = payDate == null ? null : payDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_user_store.statis
     *
     * @return the value of dwh_user_store.statis
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public Integer getStatis() {
        return statis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_user_store.statis
     *
     * @param statis the value for dwh_user_store.statis
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setStatis(Integer statis) {
        this.statis = statis;
    }
}