package com.dwh.payweb.entity;

public class RecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_user_store.Username
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_user_store.StoreId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private Integer storeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_user_store.discernId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private Integer discernid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_user_store.Username
     *
     * @return the value of dwh_user_store.Username
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_user_store.Username
     *
     * @param username the value for dwh_user_store.Username
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_user_store.StoreId
     *
     * @return the value of dwh_user_store.StoreId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_user_store.StoreId
     *
     * @param storeid the value for dwh_user_store.StoreId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_user_store.discernId
     *
     * @return the value of dwh_user_store.discernId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public Integer getDiscernid() {
        return discernid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_user_store.discernId
     *
     * @param discernid the value for dwh_user_store.discernId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setDiscernid(Integer discernid) {
        this.discernid = discernid;
    }
}