package com.dwh.payweb.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_user.UserId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_user.Password
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_user.UserName
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_user.Phonenumber
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private String phonenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_user.Type
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_user.Apayid
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    private String apayid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_user.UserId
     *
     * @return the value of dwh_user.UserId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_user.UserId
     *
     * @param userid the value for dwh_user.UserId
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_user.Password
     *
     * @return the value of dwh_user.Password
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_user.Password
     *
     * @param password the value for dwh_user.Password
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_user.UserName
     *
     * @return the value of dwh_user.UserName
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_user.UserName
     *
     * @param username the value for dwh_user.UserName
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_user.Phonenumber
     *
     * @return the value of dwh_user.Phonenumber
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_user.Phonenumber
     *
     * @param phonenumber the value for dwh_user.Phonenumber
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_user.Type
     *
     * @return the value of dwh_user.Type
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_user.Type
     *
     * @param type the value for dwh_user.Type
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_user.Apayid
     *
     * @return the value of dwh_user.Apayid
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public String getApayid() {
        return apayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_user.Apayid
     *
     * @param apayid the value for dwh_user.Apayid
     *
     * @mbg.generated Fri May 22 18:32:04 CST 2020
     */
    public void setApayid(String apayid) {
        this.apayid = apayid == null ? null : apayid.trim();
    }
}