package com.dwh.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InvalidCommparaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public InvalidCommparaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andParaCodeIsNull() {
            addCriterion("PARA_CODE is null");
            return (Criteria) this;
        }

        public Criteria andParaCodeIsNotNull() {
            addCriterion("PARA_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andParaCodeEqualTo(String value) {
            addCriterion("PARA_CODE =", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeNotEqualTo(String value) {
            addCriterion("PARA_CODE <>", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeGreaterThan(String value) {
            addCriterion("PARA_CODE >", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PARA_CODE >=", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeLessThan(String value) {
            addCriterion("PARA_CODE <", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeLessThanOrEqualTo(String value) {
            addCriterion("PARA_CODE <=", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeLike(String value) {
            addCriterion("PARA_CODE like", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeNotLike(String value) {
            addCriterion("PARA_CODE not like", value, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeIn(List<String> values) {
            addCriterion("PARA_CODE in", values, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeNotIn(List<String> values) {
            addCriterion("PARA_CODE not in", values, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeBetween(String value1, String value2) {
            addCriterion("PARA_CODE between", value1, value2, "paraCode");
            return (Criteria) this;
        }

        public Criteria andParaCodeNotBetween(String value1, String value2) {
            addCriterion("PARA_CODE not between", value1, value2, "paraCode");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeIsNull() {
            addCriterion("EPARCHY_CODE is null");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeIsNotNull() {
            addCriterion("EPARCHY_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeEqualTo(String value) {
            addCriterion("EPARCHY_CODE =", value, "eparchyCode");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeNotEqualTo(String value) {
            addCriterion("EPARCHY_CODE <>", value, "eparchyCode");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeGreaterThan(String value) {
            addCriterion("EPARCHY_CODE >", value, "eparchyCode");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("EPARCHY_CODE >=", value, "eparchyCode");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeLessThan(String value) {
            addCriterion("EPARCHY_CODE <", value, "eparchyCode");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeLessThanOrEqualTo(String value) {
            addCriterion("EPARCHY_CODE <=", value, "eparchyCode");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeLike(String value) {
            addCriterion("EPARCHY_CODE like", value, "eparchyCode");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeNotLike(String value) {
            addCriterion("EPARCHY_CODE not like", value, "eparchyCode");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeIn(List<String> values) {
            addCriterion("EPARCHY_CODE in", values, "eparchyCode");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeNotIn(List<String> values) {
            addCriterion("EPARCHY_CODE not in", values, "eparchyCode");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeBetween(String value1, String value2) {
            addCriterion("EPARCHY_CODE between", value1, value2, "eparchyCode");
            return (Criteria) this;
        }

        public Criteria andEparchyCodeNotBetween(String value1, String value2) {
            addCriterion("EPARCHY_CODE not between", value1, value2, "eparchyCode");
            return (Criteria) this;
        }

        public Criteria andParaAttrIsNull() {
            addCriterion("PARA_ATTR is null");
            return (Criteria) this;
        }

        public Criteria andParaAttrIsNotNull() {
            addCriterion("PARA_ATTR is not null");
            return (Criteria) this;
        }

        public Criteria andParaAttrEqualTo(Long value) {
            addCriterion("PARA_ATTR =", value, "paraAttr");
            return (Criteria) this;
        }

        public Criteria andParaAttrNotEqualTo(Long value) {
            addCriterion("PARA_ATTR <>", value, "paraAttr");
            return (Criteria) this;
        }

        public Criteria andParaAttrGreaterThan(Long value) {
            addCriterion("PARA_ATTR >", value, "paraAttr");
            return (Criteria) this;
        }

        public Criteria andParaAttrGreaterThanOrEqualTo(Long value) {
            addCriterion("PARA_ATTR >=", value, "paraAttr");
            return (Criteria) this;
        }

        public Criteria andParaAttrLessThan(Long value) {
            addCriterion("PARA_ATTR <", value, "paraAttr");
            return (Criteria) this;
        }

        public Criteria andParaAttrLessThanOrEqualTo(Long value) {
            addCriterion("PARA_ATTR <=", value, "paraAttr");
            return (Criteria) this;
        }

        public Criteria andParaAttrIn(List<Long> values) {
            addCriterion("PARA_ATTR in", values, "paraAttr");
            return (Criteria) this;
        }

        public Criteria andParaAttrNotIn(List<Long> values) {
            addCriterion("PARA_ATTR not in", values, "paraAttr");
            return (Criteria) this;
        }

        public Criteria andParaAttrBetween(Long value1, Long value2) {
            addCriterion("PARA_ATTR between", value1, value2, "paraAttr");
            return (Criteria) this;
        }

        public Criteria andParaAttrNotBetween(Long value1, Long value2) {
            addCriterion("PARA_ATTR not between", value1, value2, "paraAttr");
            return (Criteria) this;
        }

        public Criteria andParaNameIsNull() {
            addCriterion("PARA_NAME is null");
            return (Criteria) this;
        }

        public Criteria andParaNameIsNotNull() {
            addCriterion("PARA_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andParaNameEqualTo(String value) {
            addCriterion("PARA_NAME =", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameNotEqualTo(String value) {
            addCriterion("PARA_NAME <>", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameGreaterThan(String value) {
            addCriterion("PARA_NAME >", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameGreaterThanOrEqualTo(String value) {
            addCriterion("PARA_NAME >=", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameLessThan(String value) {
            addCriterion("PARA_NAME <", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameLessThanOrEqualTo(String value) {
            addCriterion("PARA_NAME <=", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameLike(String value) {
            addCriterion("PARA_NAME like", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameNotLike(String value) {
            addCriterion("PARA_NAME not like", value, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameIn(List<String> values) {
            addCriterion("PARA_NAME in", values, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameNotIn(List<String> values) {
            addCriterion("PARA_NAME not in", values, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameBetween(String value1, String value2) {
            addCriterion("PARA_NAME between", value1, value2, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaNameNotBetween(String value1, String value2) {
            addCriterion("PARA_NAME not between", value1, value2, "paraName");
            return (Criteria) this;
        }

        public Criteria andParaCode1IsNull() {
            addCriterion("PARA_CODE1 is null");
            return (Criteria) this;
        }

        public Criteria andParaCode1IsNotNull() {
            addCriterion("PARA_CODE1 is not null");
            return (Criteria) this;
        }

        public Criteria andParaCode1EqualTo(String value) {
            addCriterion("PARA_CODE1 =", value, "paraCode1");
            return (Criteria) this;
        }

        public Criteria andParaCode1NotEqualTo(String value) {
            addCriterion("PARA_CODE1 <>", value, "paraCode1");
            return (Criteria) this;
        }

        public Criteria andParaCode1GreaterThan(String value) {
            addCriterion("PARA_CODE1 >", value, "paraCode1");
            return (Criteria) this;
        }

        public Criteria andParaCode1GreaterThanOrEqualTo(String value) {
            addCriterion("PARA_CODE1 >=", value, "paraCode1");
            return (Criteria) this;
        }

        public Criteria andParaCode1LessThan(String value) {
            addCriterion("PARA_CODE1 <", value, "paraCode1");
            return (Criteria) this;
        }

        public Criteria andParaCode1LessThanOrEqualTo(String value) {
            addCriterion("PARA_CODE1 <=", value, "paraCode1");
            return (Criteria) this;
        }

        public Criteria andParaCode1Like(String value) {
            addCriterion("PARA_CODE1 like", value, "paraCode1");
            return (Criteria) this;
        }

        public Criteria andParaCode1NotLike(String value) {
            addCriterion("PARA_CODE1 not like", value, "paraCode1");
            return (Criteria) this;
        }

        public Criteria andParaCode1In(List<String> values) {
            addCriterion("PARA_CODE1 in", values, "paraCode1");
            return (Criteria) this;
        }

        public Criteria andParaCode1NotIn(List<String> values) {
            addCriterion("PARA_CODE1 not in", values, "paraCode1");
            return (Criteria) this;
        }

        public Criteria andParaCode1Between(String value1, String value2) {
            addCriterion("PARA_CODE1 between", value1, value2, "paraCode1");
            return (Criteria) this;
        }

        public Criteria andParaCode1NotBetween(String value1, String value2) {
            addCriterion("PARA_CODE1 not between", value1, value2, "paraCode1");
            return (Criteria) this;
        }

        public Criteria andParaCode2IsNull() {
            addCriterion("PARA_CODE2 is null");
            return (Criteria) this;
        }

        public Criteria andParaCode2IsNotNull() {
            addCriterion("PARA_CODE2 is not null");
            return (Criteria) this;
        }

        public Criteria andParaCode2EqualTo(String value) {
            addCriterion("PARA_CODE2 =", value, "paraCode2");
            return (Criteria) this;
        }

        public Criteria andParaCode2NotEqualTo(String value) {
            addCriterion("PARA_CODE2 <>", value, "paraCode2");
            return (Criteria) this;
        }

        public Criteria andParaCode2GreaterThan(String value) {
            addCriterion("PARA_CODE2 >", value, "paraCode2");
            return (Criteria) this;
        }

        public Criteria andParaCode2GreaterThanOrEqualTo(String value) {
            addCriterion("PARA_CODE2 >=", value, "paraCode2");
            return (Criteria) this;
        }

        public Criteria andParaCode2LessThan(String value) {
            addCriterion("PARA_CODE2 <", value, "paraCode2");
            return (Criteria) this;
        }

        public Criteria andParaCode2LessThanOrEqualTo(String value) {
            addCriterion("PARA_CODE2 <=", value, "paraCode2");
            return (Criteria) this;
        }

        public Criteria andParaCode2Like(String value) {
            addCriterion("PARA_CODE2 like", value, "paraCode2");
            return (Criteria) this;
        }

        public Criteria andParaCode2NotLike(String value) {
            addCriterion("PARA_CODE2 not like", value, "paraCode2");
            return (Criteria) this;
        }

        public Criteria andParaCode2In(List<String> values) {
            addCriterion("PARA_CODE2 in", values, "paraCode2");
            return (Criteria) this;
        }

        public Criteria andParaCode2NotIn(List<String> values) {
            addCriterion("PARA_CODE2 not in", values, "paraCode2");
            return (Criteria) this;
        }

        public Criteria andParaCode2Between(String value1, String value2) {
            addCriterion("PARA_CODE2 between", value1, value2, "paraCode2");
            return (Criteria) this;
        }

        public Criteria andParaCode2NotBetween(String value1, String value2) {
            addCriterion("PARA_CODE2 not between", value1, value2, "paraCode2");
            return (Criteria) this;
        }

        public Criteria andParaCode3IsNull() {
            addCriterion("PARA_CODE3 is null");
            return (Criteria) this;
        }

        public Criteria andParaCode3IsNotNull() {
            addCriterion("PARA_CODE3 is not null");
            return (Criteria) this;
        }

        public Criteria andParaCode3EqualTo(String value) {
            addCriterion("PARA_CODE3 =", value, "paraCode3");
            return (Criteria) this;
        }

        public Criteria andParaCode3NotEqualTo(String value) {
            addCriterion("PARA_CODE3 <>", value, "paraCode3");
            return (Criteria) this;
        }

        public Criteria andParaCode3GreaterThan(String value) {
            addCriterion("PARA_CODE3 >", value, "paraCode3");
            return (Criteria) this;
        }

        public Criteria andParaCode3GreaterThanOrEqualTo(String value) {
            addCriterion("PARA_CODE3 >=", value, "paraCode3");
            return (Criteria) this;
        }

        public Criteria andParaCode3LessThan(String value) {
            addCriterion("PARA_CODE3 <", value, "paraCode3");
            return (Criteria) this;
        }

        public Criteria andParaCode3LessThanOrEqualTo(String value) {
            addCriterion("PARA_CODE3 <=", value, "paraCode3");
            return (Criteria) this;
        }

        public Criteria andParaCode3Like(String value) {
            addCriterion("PARA_CODE3 like", value, "paraCode3");
            return (Criteria) this;
        }

        public Criteria andParaCode3NotLike(String value) {
            addCriterion("PARA_CODE3 not like", value, "paraCode3");
            return (Criteria) this;
        }

        public Criteria andParaCode3In(List<String> values) {
            addCriterion("PARA_CODE3 in", values, "paraCode3");
            return (Criteria) this;
        }

        public Criteria andParaCode3NotIn(List<String> values) {
            addCriterion("PARA_CODE3 not in", values, "paraCode3");
            return (Criteria) this;
        }

        public Criteria andParaCode3Between(String value1, String value2) {
            addCriterion("PARA_CODE3 between", value1, value2, "paraCode3");
            return (Criteria) this;
        }

        public Criteria andParaCode3NotBetween(String value1, String value2) {
            addCriterion("PARA_CODE3 not between", value1, value2, "paraCode3");
            return (Criteria) this;
        }

        public Criteria andParaCode4IsNull() {
            addCriterion("PARA_CODE4 is null");
            return (Criteria) this;
        }

        public Criteria andParaCode4IsNotNull() {
            addCriterion("PARA_CODE4 is not null");
            return (Criteria) this;
        }

        public Criteria andParaCode4EqualTo(String value) {
            addCriterion("PARA_CODE4 =", value, "paraCode4");
            return (Criteria) this;
        }

        public Criteria andParaCode4NotEqualTo(String value) {
            addCriterion("PARA_CODE4 <>", value, "paraCode4");
            return (Criteria) this;
        }

        public Criteria andParaCode4GreaterThan(String value) {
            addCriterion("PARA_CODE4 >", value, "paraCode4");
            return (Criteria) this;
        }

        public Criteria andParaCode4GreaterThanOrEqualTo(String value) {
            addCriterion("PARA_CODE4 >=", value, "paraCode4");
            return (Criteria) this;
        }

        public Criteria andParaCode4LessThan(String value) {
            addCriterion("PARA_CODE4 <", value, "paraCode4");
            return (Criteria) this;
        }

        public Criteria andParaCode4LessThanOrEqualTo(String value) {
            addCriterion("PARA_CODE4 <=", value, "paraCode4");
            return (Criteria) this;
        }

        public Criteria andParaCode4Like(String value) {
            addCriterion("PARA_CODE4 like", value, "paraCode4");
            return (Criteria) this;
        }

        public Criteria andParaCode4NotLike(String value) {
            addCriterion("PARA_CODE4 not like", value, "paraCode4");
            return (Criteria) this;
        }

        public Criteria andParaCode4In(List<String> values) {
            addCriterion("PARA_CODE4 in", values, "paraCode4");
            return (Criteria) this;
        }

        public Criteria andParaCode4NotIn(List<String> values) {
            addCriterion("PARA_CODE4 not in", values, "paraCode4");
            return (Criteria) this;
        }

        public Criteria andParaCode4Between(String value1, String value2) {
            addCriterion("PARA_CODE4 between", value1, value2, "paraCode4");
            return (Criteria) this;
        }

        public Criteria andParaCode4NotBetween(String value1, String value2) {
            addCriterion("PARA_CODE4 not between", value1, value2, "paraCode4");
            return (Criteria) this;
        }

        public Criteria andParaCode5IsNull() {
            addCriterion("PARA_CODE5 is null");
            return (Criteria) this;
        }

        public Criteria andParaCode5IsNotNull() {
            addCriterion("PARA_CODE5 is not null");
            return (Criteria) this;
        }

        public Criteria andParaCode5EqualTo(String value) {
            addCriterion("PARA_CODE5 =", value, "paraCode5");
            return (Criteria) this;
        }

        public Criteria andParaCode5NotEqualTo(String value) {
            addCriterion("PARA_CODE5 <>", value, "paraCode5");
            return (Criteria) this;
        }

        public Criteria andParaCode5GreaterThan(String value) {
            addCriterion("PARA_CODE5 >", value, "paraCode5");
            return (Criteria) this;
        }

        public Criteria andParaCode5GreaterThanOrEqualTo(String value) {
            addCriterion("PARA_CODE5 >=", value, "paraCode5");
            return (Criteria) this;
        }

        public Criteria andParaCode5LessThan(String value) {
            addCriterion("PARA_CODE5 <", value, "paraCode5");
            return (Criteria) this;
        }

        public Criteria andParaCode5LessThanOrEqualTo(String value) {
            addCriterion("PARA_CODE5 <=", value, "paraCode5");
            return (Criteria) this;
        }

        public Criteria andParaCode5Like(String value) {
            addCriterion("PARA_CODE5 like", value, "paraCode5");
            return (Criteria) this;
        }

        public Criteria andParaCode5NotLike(String value) {
            addCriterion("PARA_CODE5 not like", value, "paraCode5");
            return (Criteria) this;
        }

        public Criteria andParaCode5In(List<String> values) {
            addCriterion("PARA_CODE5 in", values, "paraCode5");
            return (Criteria) this;
        }

        public Criteria andParaCode5NotIn(List<String> values) {
            addCriterion("PARA_CODE5 not in", values, "paraCode5");
            return (Criteria) this;
        }

        public Criteria andParaCode5Between(String value1, String value2) {
            addCriterion("PARA_CODE5 between", value1, value2, "paraCode5");
            return (Criteria) this;
        }

        public Criteria andParaCode5NotBetween(String value1, String value2) {
            addCriterion("PARA_CODE5 not between", value1, value2, "paraCode5");
            return (Criteria) this;
        }

        public Criteria andParaCode6IsNull() {
            addCriterion("PARA_CODE6 is null");
            return (Criteria) this;
        }

        public Criteria andParaCode6IsNotNull() {
            addCriterion("PARA_CODE6 is not null");
            return (Criteria) this;
        }

        public Criteria andParaCode6EqualTo(String value) {
            addCriterion("PARA_CODE6 =", value, "paraCode6");
            return (Criteria) this;
        }

        public Criteria andParaCode6NotEqualTo(String value) {
            addCriterion("PARA_CODE6 <>", value, "paraCode6");
            return (Criteria) this;
        }

        public Criteria andParaCode6GreaterThan(String value) {
            addCriterion("PARA_CODE6 >", value, "paraCode6");
            return (Criteria) this;
        }

        public Criteria andParaCode6GreaterThanOrEqualTo(String value) {
            addCriterion("PARA_CODE6 >=", value, "paraCode6");
            return (Criteria) this;
        }

        public Criteria andParaCode6LessThan(String value) {
            addCriterion("PARA_CODE6 <", value, "paraCode6");
            return (Criteria) this;
        }

        public Criteria andParaCode6LessThanOrEqualTo(String value) {
            addCriterion("PARA_CODE6 <=", value, "paraCode6");
            return (Criteria) this;
        }

        public Criteria andParaCode6Like(String value) {
            addCriterion("PARA_CODE6 like", value, "paraCode6");
            return (Criteria) this;
        }

        public Criteria andParaCode6NotLike(String value) {
            addCriterion("PARA_CODE6 not like", value, "paraCode6");
            return (Criteria) this;
        }

        public Criteria andParaCode6In(List<String> values) {
            addCriterion("PARA_CODE6 in", values, "paraCode6");
            return (Criteria) this;
        }

        public Criteria andParaCode6NotIn(List<String> values) {
            addCriterion("PARA_CODE6 not in", values, "paraCode6");
            return (Criteria) this;
        }

        public Criteria andParaCode6Between(String value1, String value2) {
            addCriterion("PARA_CODE6 between", value1, value2, "paraCode6");
            return (Criteria) this;
        }

        public Criteria andParaCode6NotBetween(String value1, String value2) {
            addCriterion("PARA_CODE6 not between", value1, value2, "paraCode6");
            return (Criteria) this;
        }

        public Criteria andParaDate7IsNull() {
            addCriterion("PARA_DATE7 is null");
            return (Criteria) this;
        }

        public Criteria andParaDate7IsNotNull() {
            addCriterion("PARA_DATE7 is not null");
            return (Criteria) this;
        }

        public Criteria andParaDate7EqualTo(Date value) {
            addCriterion("PARA_DATE7 =", value, "paraDate7");
            return (Criteria) this;
        }

        public Criteria andParaDate7NotEqualTo(Date value) {
            addCriterion("PARA_DATE7 <>", value, "paraDate7");
            return (Criteria) this;
        }

        public Criteria andParaDate7GreaterThan(Date value) {
            addCriterion("PARA_DATE7 >", value, "paraDate7");
            return (Criteria) this;
        }

        public Criteria andParaDate7GreaterThanOrEqualTo(Date value) {
            addCriterion("PARA_DATE7 >=", value, "paraDate7");
            return (Criteria) this;
        }

        public Criteria andParaDate7LessThan(Date value) {
            addCriterion("PARA_DATE7 <", value, "paraDate7");
            return (Criteria) this;
        }

        public Criteria andParaDate7LessThanOrEqualTo(Date value) {
            addCriterion("PARA_DATE7 <=", value, "paraDate7");
            return (Criteria) this;
        }

        public Criteria andParaDate7In(List<Date> values) {
            addCriterion("PARA_DATE7 in", values, "paraDate7");
            return (Criteria) this;
        }

        public Criteria andParaDate7NotIn(List<Date> values) {
            addCriterion("PARA_DATE7 not in", values, "paraDate7");
            return (Criteria) this;
        }

        public Criteria andParaDate7Between(Date value1, Date value2) {
            addCriterion("PARA_DATE7 between", value1, value2, "paraDate7");
            return (Criteria) this;
        }

        public Criteria andParaDate7NotBetween(Date value1, Date value2) {
            addCriterion("PARA_DATE7 not between", value1, value2, "paraDate7");
            return (Criteria) this;
        }

        public Criteria andParaDate8IsNull() {
            addCriterion("PARA_DATE8 is null");
            return (Criteria) this;
        }

        public Criteria andParaDate8IsNotNull() {
            addCriterion("PARA_DATE8 is not null");
            return (Criteria) this;
        }

        public Criteria andParaDate8EqualTo(Date value) {
            addCriterion("PARA_DATE8 =", value, "paraDate8");
            return (Criteria) this;
        }

        public Criteria andParaDate8NotEqualTo(Date value) {
            addCriterion("PARA_DATE8 <>", value, "paraDate8");
            return (Criteria) this;
        }

        public Criteria andParaDate8GreaterThan(Date value) {
            addCriterion("PARA_DATE8 >", value, "paraDate8");
            return (Criteria) this;
        }

        public Criteria andParaDate8GreaterThanOrEqualTo(Date value) {
            addCriterion("PARA_DATE8 >=", value, "paraDate8");
            return (Criteria) this;
        }

        public Criteria andParaDate8LessThan(Date value) {
            addCriterion("PARA_DATE8 <", value, "paraDate8");
            return (Criteria) this;
        }

        public Criteria andParaDate8LessThanOrEqualTo(Date value) {
            addCriterion("PARA_DATE8 <=", value, "paraDate8");
            return (Criteria) this;
        }

        public Criteria andParaDate8In(List<Date> values) {
            addCriterion("PARA_DATE8 in", values, "paraDate8");
            return (Criteria) this;
        }

        public Criteria andParaDate8NotIn(List<Date> values) {
            addCriterion("PARA_DATE8 not in", values, "paraDate8");
            return (Criteria) this;
        }

        public Criteria andParaDate8Between(Date value1, Date value2) {
            addCriterion("PARA_DATE8 between", value1, value2, "paraDate8");
            return (Criteria) this;
        }

        public Criteria andParaDate8NotBetween(Date value1, Date value2) {
            addCriterion("PARA_DATE8 not between", value1, value2, "paraDate8");
            return (Criteria) this;
        }

        public Criteria andParaDate9IsNull() {
            addCriterion("PARA_DATE9 is null");
            return (Criteria) this;
        }

        public Criteria andParaDate9IsNotNull() {
            addCriterion("PARA_DATE9 is not null");
            return (Criteria) this;
        }

        public Criteria andParaDate9EqualTo(Date value) {
            addCriterion("PARA_DATE9 =", value, "paraDate9");
            return (Criteria) this;
        }

        public Criteria andParaDate9NotEqualTo(Date value) {
            addCriterion("PARA_DATE9 <>", value, "paraDate9");
            return (Criteria) this;
        }

        public Criteria andParaDate9GreaterThan(Date value) {
            addCriterion("PARA_DATE9 >", value, "paraDate9");
            return (Criteria) this;
        }

        public Criteria andParaDate9GreaterThanOrEqualTo(Date value) {
            addCriterion("PARA_DATE9 >=", value, "paraDate9");
            return (Criteria) this;
        }

        public Criteria andParaDate9LessThan(Date value) {
            addCriterion("PARA_DATE9 <", value, "paraDate9");
            return (Criteria) this;
        }

        public Criteria andParaDate9LessThanOrEqualTo(Date value) {
            addCriterion("PARA_DATE9 <=", value, "paraDate9");
            return (Criteria) this;
        }

        public Criteria andParaDate9In(List<Date> values) {
            addCriterion("PARA_DATE9 in", values, "paraDate9");
            return (Criteria) this;
        }

        public Criteria andParaDate9NotIn(List<Date> values) {
            addCriterion("PARA_DATE9 not in", values, "paraDate9");
            return (Criteria) this;
        }

        public Criteria andParaDate9Between(Date value1, Date value2) {
            addCriterion("PARA_DATE9 between", value1, value2, "paraDate9");
            return (Criteria) this;
        }

        public Criteria andParaDate9NotBetween(Date value1, Date value2) {
            addCriterion("PARA_DATE9 not between", value1, value2, "paraDate9");
            return (Criteria) this;
        }

        public Criteria andParaDate10IsNull() {
            addCriterion("PARA_DATE10 is null");
            return (Criteria) this;
        }

        public Criteria andParaDate10IsNotNull() {
            addCriterion("PARA_DATE10 is not null");
            return (Criteria) this;
        }

        public Criteria andParaDate10EqualTo(Date value) {
            addCriterion("PARA_DATE10 =", value, "paraDate10");
            return (Criteria) this;
        }

        public Criteria andParaDate10NotEqualTo(Date value) {
            addCriterion("PARA_DATE10 <>", value, "paraDate10");
            return (Criteria) this;
        }

        public Criteria andParaDate10GreaterThan(Date value) {
            addCriterion("PARA_DATE10 >", value, "paraDate10");
            return (Criteria) this;
        }

        public Criteria andParaDate10GreaterThanOrEqualTo(Date value) {
            addCriterion("PARA_DATE10 >=", value, "paraDate10");
            return (Criteria) this;
        }

        public Criteria andParaDate10LessThan(Date value) {
            addCriterion("PARA_DATE10 <", value, "paraDate10");
            return (Criteria) this;
        }

        public Criteria andParaDate10LessThanOrEqualTo(Date value) {
            addCriterion("PARA_DATE10 <=", value, "paraDate10");
            return (Criteria) this;
        }

        public Criteria andParaDate10In(List<Date> values) {
            addCriterion("PARA_DATE10 in", values, "paraDate10");
            return (Criteria) this;
        }

        public Criteria andParaDate10NotIn(List<Date> values) {
            addCriterion("PARA_DATE10 not in", values, "paraDate10");
            return (Criteria) this;
        }

        public Criteria andParaDate10Between(Date value1, Date value2) {
            addCriterion("PARA_DATE10 between", value1, value2, "paraDate10");
            return (Criteria) this;
        }

        public Criteria andParaDate10NotBetween(Date value1, Date value2) {
            addCriterion("PARA_DATE10 not between", value1, value2, "paraDate10");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("START_DATE is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("START_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterion("START_DATE =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterion("START_DATE <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterion("START_DATE >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("START_DATE >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterion("START_DATE <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterion("START_DATE <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterion("START_DATE in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterion("START_DATE not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterion("START_DATE between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterion("START_DATE not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterion("END_DATE =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterion("END_DATE <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterion("END_DATE >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("END_DATE >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterion("END_DATE <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterion("END_DATE <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterion("END_DATE in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterion("END_DATE not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterion("END_DATE between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterion("END_DATE not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andUseTagIsNull() {
            addCriterion("USE_TAG is null");
            return (Criteria) this;
        }

        public Criteria andUseTagIsNotNull() {
            addCriterion("USE_TAG is not null");
            return (Criteria) this;
        }

        public Criteria andUseTagEqualTo(String value) {
            addCriterion("USE_TAG =", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagNotEqualTo(String value) {
            addCriterion("USE_TAG <>", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagGreaterThan(String value) {
            addCriterion("USE_TAG >", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagGreaterThanOrEqualTo(String value) {
            addCriterion("USE_TAG >=", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagLessThan(String value) {
            addCriterion("USE_TAG <", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagLessThanOrEqualTo(String value) {
            addCriterion("USE_TAG <=", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagLike(String value) {
            addCriterion("USE_TAG like", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagNotLike(String value) {
            addCriterion("USE_TAG not like", value, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagIn(List<String> values) {
            addCriterion("USE_TAG in", values, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagNotIn(List<String> values) {
            addCriterion("USE_TAG not in", values, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagBetween(String value1, String value2) {
            addCriterion("USE_TAG between", value1, value2, "useTag");
            return (Criteria) this;
        }

        public Criteria andUseTagNotBetween(String value1, String value2) {
            addCriterion("USE_TAG not between", value1, value2, "useTag");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeIsNull() {
            addCriterion("UPDATE_EPARCHY_CODE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeIsNotNull() {
            addCriterion("UPDATE_EPARCHY_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeEqualTo(String value) {
            addCriterion("UPDATE_EPARCHY_CODE =", value, "updateEparchyCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeNotEqualTo(String value) {
            addCriterion("UPDATE_EPARCHY_CODE <>", value, "updateEparchyCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeGreaterThan(String value) {
            addCriterion("UPDATE_EPARCHY_CODE >", value, "updateEparchyCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_EPARCHY_CODE >=", value, "updateEparchyCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeLessThan(String value) {
            addCriterion("UPDATE_EPARCHY_CODE <", value, "updateEparchyCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_EPARCHY_CODE <=", value, "updateEparchyCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeLike(String value) {
            addCriterion("UPDATE_EPARCHY_CODE like", value, "updateEparchyCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeNotLike(String value) {
            addCriterion("UPDATE_EPARCHY_CODE not like", value, "updateEparchyCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeIn(List<String> values) {
            addCriterion("UPDATE_EPARCHY_CODE in", values, "updateEparchyCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeNotIn(List<String> values) {
            addCriterion("UPDATE_EPARCHY_CODE not in", values, "updateEparchyCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeBetween(String value1, String value2) {
            addCriterion("UPDATE_EPARCHY_CODE between", value1, value2, "updateEparchyCode");
            return (Criteria) this;
        }

        public Criteria andUpdateEparchyCodeNotBetween(String value1, String value2) {
            addCriterion("UPDATE_EPARCHY_CODE not between", value1, value2, "updateEparchyCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeIsNull() {
            addCriterion("UPDATE_CITY_CODE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeIsNotNull() {
            addCriterion("UPDATE_CITY_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeEqualTo(String value) {
            addCriterion("UPDATE_CITY_CODE =", value, "updateCityCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeNotEqualTo(String value) {
            addCriterion("UPDATE_CITY_CODE <>", value, "updateCityCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeGreaterThan(String value) {
            addCriterion("UPDATE_CITY_CODE >", value, "updateCityCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_CITY_CODE >=", value, "updateCityCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeLessThan(String value) {
            addCriterion("UPDATE_CITY_CODE <", value, "updateCityCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_CITY_CODE <=", value, "updateCityCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeLike(String value) {
            addCriterion("UPDATE_CITY_CODE like", value, "updateCityCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeNotLike(String value) {
            addCriterion("UPDATE_CITY_CODE not like", value, "updateCityCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeIn(List<String> values) {
            addCriterion("UPDATE_CITY_CODE in", values, "updateCityCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeNotIn(List<String> values) {
            addCriterion("UPDATE_CITY_CODE not in", values, "updateCityCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeBetween(String value1, String value2) {
            addCriterion("UPDATE_CITY_CODE between", value1, value2, "updateCityCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCityCodeNotBetween(String value1, String value2) {
            addCriterion("UPDATE_CITY_CODE not between", value1, value2, "updateCityCode");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdIsNull() {
            addCriterion("UPDATE_DEPART_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdIsNotNull() {
            addCriterion("UPDATE_DEPART_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdEqualTo(String value) {
            addCriterion("UPDATE_DEPART_ID =", value, "updateDepartId");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdNotEqualTo(String value) {
            addCriterion("UPDATE_DEPART_ID <>", value, "updateDepartId");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdGreaterThan(String value) {
            addCriterion("UPDATE_DEPART_ID >", value, "updateDepartId");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_DEPART_ID >=", value, "updateDepartId");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdLessThan(String value) {
            addCriterion("UPDATE_DEPART_ID <", value, "updateDepartId");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_DEPART_ID <=", value, "updateDepartId");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdLike(String value) {
            addCriterion("UPDATE_DEPART_ID like", value, "updateDepartId");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdNotLike(String value) {
            addCriterion("UPDATE_DEPART_ID not like", value, "updateDepartId");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdIn(List<String> values) {
            addCriterion("UPDATE_DEPART_ID in", values, "updateDepartId");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdNotIn(List<String> values) {
            addCriterion("UPDATE_DEPART_ID not in", values, "updateDepartId");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdBetween(String value1, String value2) {
            addCriterion("UPDATE_DEPART_ID between", value1, value2, "updateDepartId");
            return (Criteria) this;
        }

        public Criteria andUpdateDepartIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_DEPART_ID not between", value1, value2, "updateDepartId");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdIsNull() {
            addCriterion("UPDATE_STAFF_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdIsNotNull() {
            addCriterion("UPDATE_STAFF_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdEqualTo(String value) {
            addCriterion("UPDATE_STAFF_ID =", value, "updateStaffId");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdNotEqualTo(String value) {
            addCriterion("UPDATE_STAFF_ID <>", value, "updateStaffId");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdGreaterThan(String value) {
            addCriterion("UPDATE_STAFF_ID >", value, "updateStaffId");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_STAFF_ID >=", value, "updateStaffId");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdLessThan(String value) {
            addCriterion("UPDATE_STAFF_ID <", value, "updateStaffId");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_STAFF_ID <=", value, "updateStaffId");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdLike(String value) {
            addCriterion("UPDATE_STAFF_ID like", value, "updateStaffId");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdNotLike(String value) {
            addCriterion("UPDATE_STAFF_ID not like", value, "updateStaffId");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdIn(List<String> values) {
            addCriterion("UPDATE_STAFF_ID in", values, "updateStaffId");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdNotIn(List<String> values) {
            addCriterion("UPDATE_STAFF_ID not in", values, "updateStaffId");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdBetween(String value1, String value2) {
            addCriterion("UPDATE_STAFF_ID between", value1, value2, "updateStaffId");
            return (Criteria) this;
        }

        public Criteria andUpdateStaffIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_STAFF_ID not between", value1, value2, "updateStaffId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table td_b_commpara
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 13 10:22:12 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table td_b_commpara
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}