package com.dwh.entity;

import java.util.Date;

public class InvalidCommpara {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.PARA_CODE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String paraCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.EPARCHY_CODE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String eparchyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.PARA_ATTR
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private Long paraAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.PARA_NAME
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String paraName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.PARA_CODE1
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String paraCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.PARA_CODE2
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String paraCode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.PARA_CODE3
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String paraCode3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.PARA_CODE4
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String paraCode4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.PARA_CODE5
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String paraCode5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.PARA_CODE6
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String paraCode6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.PARA_DATE7
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private Date paraDate7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.PARA_DATE8
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private Date paraDate8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.PARA_DATE9
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private Date paraDate9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.PARA_DATE10
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private Date paraDate10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.START_DATE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.END_DATE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.USE_TAG
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String useTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.REMARK
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.UPDATE_EPARCHY_CODE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String updateEparchyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.UPDATE_CITY_CODE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String updateCityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.UPDATE_DEPART_ID
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String updateDepartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column td_b_commpara.UPDATE_STAFF_ID
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    private String updateStaffId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.PARA_CODE
     *
     * @return the value of td_b_commpara.PARA_CODE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getParaCode() {
        return paraCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.PARA_CODE
     *
     * @param paraCode the value for td_b_commpara.PARA_CODE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setParaCode(String paraCode) {
        this.paraCode = paraCode == null ? null : paraCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.EPARCHY_CODE
     *
     * @return the value of td_b_commpara.EPARCHY_CODE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getEparchyCode() {
        return eparchyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.EPARCHY_CODE
     *
     * @param eparchyCode the value for td_b_commpara.EPARCHY_CODE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setEparchyCode(String eparchyCode) {
        this.eparchyCode = eparchyCode == null ? null : eparchyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.PARA_ATTR
     *
     * @return the value of td_b_commpara.PARA_ATTR
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public Long getParaAttr() {
        return paraAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.PARA_ATTR
     *
     * @param paraAttr the value for td_b_commpara.PARA_ATTR
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setParaAttr(Long paraAttr) {
        this.paraAttr = paraAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.PARA_NAME
     *
     * @return the value of td_b_commpara.PARA_NAME
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getParaName() {
        return paraName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.PARA_NAME
     *
     * @param paraName the value for td_b_commpara.PARA_NAME
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setParaName(String paraName) {
        this.paraName = paraName == null ? null : paraName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.PARA_CODE1
     *
     * @return the value of td_b_commpara.PARA_CODE1
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getParaCode1() {
        return paraCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.PARA_CODE1
     *
     * @param paraCode1 the value for td_b_commpara.PARA_CODE1
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setParaCode1(String paraCode1) {
        this.paraCode1 = paraCode1 == null ? null : paraCode1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.PARA_CODE2
     *
     * @return the value of td_b_commpara.PARA_CODE2
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getParaCode2() {
        return paraCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.PARA_CODE2
     *
     * @param paraCode2 the value for td_b_commpara.PARA_CODE2
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setParaCode2(String paraCode2) {
        this.paraCode2 = paraCode2 == null ? null : paraCode2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.PARA_CODE3
     *
     * @return the value of td_b_commpara.PARA_CODE3
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getParaCode3() {
        return paraCode3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.PARA_CODE3
     *
     * @param paraCode3 the value for td_b_commpara.PARA_CODE3
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setParaCode3(String paraCode3) {
        this.paraCode3 = paraCode3 == null ? null : paraCode3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.PARA_CODE4
     *
     * @return the value of td_b_commpara.PARA_CODE4
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getParaCode4() {
        return paraCode4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.PARA_CODE4
     *
     * @param paraCode4 the value for td_b_commpara.PARA_CODE4
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setParaCode4(String paraCode4) {
        this.paraCode4 = paraCode4 == null ? null : paraCode4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.PARA_CODE5
     *
     * @return the value of td_b_commpara.PARA_CODE5
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getParaCode5() {
        return paraCode5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.PARA_CODE5
     *
     * @param paraCode5 the value for td_b_commpara.PARA_CODE5
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setParaCode5(String paraCode5) {
        this.paraCode5 = paraCode5 == null ? null : paraCode5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.PARA_CODE6
     *
     * @return the value of td_b_commpara.PARA_CODE6
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getParaCode6() {
        return paraCode6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.PARA_CODE6
     *
     * @param paraCode6 the value for td_b_commpara.PARA_CODE6
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setParaCode6(String paraCode6) {
        this.paraCode6 = paraCode6 == null ? null : paraCode6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.PARA_DATE7
     *
     * @return the value of td_b_commpara.PARA_DATE7
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public Date getParaDate7() {
        return paraDate7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.PARA_DATE7
     *
     * @param paraDate7 the value for td_b_commpara.PARA_DATE7
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setParaDate7(Date paraDate7) {
        this.paraDate7 = paraDate7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.PARA_DATE8
     *
     * @return the value of td_b_commpara.PARA_DATE8
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public Date getParaDate8() {
        return paraDate8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.PARA_DATE8
     *
     * @param paraDate8 the value for td_b_commpara.PARA_DATE8
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setParaDate8(Date paraDate8) {
        this.paraDate8 = paraDate8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.PARA_DATE9
     *
     * @return the value of td_b_commpara.PARA_DATE9
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public Date getParaDate9() {
        return paraDate9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.PARA_DATE9
     *
     * @param paraDate9 the value for td_b_commpara.PARA_DATE9
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setParaDate9(Date paraDate9) {
        this.paraDate9 = paraDate9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.PARA_DATE10
     *
     * @return the value of td_b_commpara.PARA_DATE10
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public Date getParaDate10() {
        return paraDate10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.PARA_DATE10
     *
     * @param paraDate10 the value for td_b_commpara.PARA_DATE10
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setParaDate10(Date paraDate10) {
        this.paraDate10 = paraDate10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.START_DATE
     *
     * @return the value of td_b_commpara.START_DATE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.START_DATE
     *
     * @param startDate the value for td_b_commpara.START_DATE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.END_DATE
     *
     * @return the value of td_b_commpara.END_DATE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.END_DATE
     *
     * @param endDate the value for td_b_commpara.END_DATE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.USE_TAG
     *
     * @return the value of td_b_commpara.USE_TAG
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getUseTag() {
        return useTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.USE_TAG
     *
     * @param useTag the value for td_b_commpara.USE_TAG
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setUseTag(String useTag) {
        this.useTag = useTag == null ? null : useTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.REMARK
     *
     * @return the value of td_b_commpara.REMARK
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.REMARK
     *
     * @param remark the value for td_b_commpara.REMARK
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.UPDATE_TIME
     *
     * @return the value of td_b_commpara.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.UPDATE_TIME
     *
     * @param updateTime the value for td_b_commpara.UPDATE_TIME
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.UPDATE_EPARCHY_CODE
     *
     * @return the value of td_b_commpara.UPDATE_EPARCHY_CODE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getUpdateEparchyCode() {
        return updateEparchyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.UPDATE_EPARCHY_CODE
     *
     * @param updateEparchyCode the value for td_b_commpara.UPDATE_EPARCHY_CODE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setUpdateEparchyCode(String updateEparchyCode) {
        this.updateEparchyCode = updateEparchyCode == null ? null : updateEparchyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.UPDATE_CITY_CODE
     *
     * @return the value of td_b_commpara.UPDATE_CITY_CODE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getUpdateCityCode() {
        return updateCityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.UPDATE_CITY_CODE
     *
     * @param updateCityCode the value for td_b_commpara.UPDATE_CITY_CODE
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setUpdateCityCode(String updateCityCode) {
        this.updateCityCode = updateCityCode == null ? null : updateCityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.UPDATE_DEPART_ID
     *
     * @return the value of td_b_commpara.UPDATE_DEPART_ID
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getUpdateDepartId() {
        return updateDepartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.UPDATE_DEPART_ID
     *
     * @param updateDepartId the value for td_b_commpara.UPDATE_DEPART_ID
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setUpdateDepartId(String updateDepartId) {
        this.updateDepartId = updateDepartId == null ? null : updateDepartId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column td_b_commpara.UPDATE_STAFF_ID
     *
     * @return the value of td_b_commpara.UPDATE_STAFF_ID
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public String getUpdateStaffId() {
        return updateStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column td_b_commpara.UPDATE_STAFF_ID
     *
     * @param updateStaffId the value for td_b_commpara.UPDATE_STAFF_ID
     *
     * @mbggenerated Tue Aug 13 10:22:12 CST 2019
     */
    public void setUpdateStaffId(String updateStaffId) {
        this.updateStaffId = updateStaffId == null ? null : updateStaffId.trim();
    }
}