package com.dwh.payweb.entity;

import java.util.ArrayList;
import java.util.List;

public class BusinessExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    public BusinessExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBusinidIsNull() {
            addCriterion("BusinId is null");
            return (Criteria) this;
        }

        public Criteria andBusinidIsNotNull() {
            addCriterion("BusinId is not null");
            return (Criteria) this;
        }

        public Criteria andBusinidEqualTo(Integer value) {
            addCriterion("BusinId =", value, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidNotEqualTo(Integer value) {
            addCriterion("BusinId <>", value, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidGreaterThan(Integer value) {
            addCriterion("BusinId >", value, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidGreaterThanOrEqualTo(Integer value) {
            addCriterion("BusinId >=", value, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidLessThan(Integer value) {
            addCriterion("BusinId <", value, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidLessThanOrEqualTo(Integer value) {
            addCriterion("BusinId <=", value, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidIn(List<Integer> values) {
            addCriterion("BusinId in", values, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidNotIn(List<Integer> values) {
            addCriterion("BusinId not in", values, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidBetween(Integer value1, Integer value2) {
            addCriterion("BusinId between", value1, value2, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinidNotBetween(Integer value1, Integer value2) {
            addCriterion("BusinId not between", value1, value2, "businid");
            return (Criteria) this;
        }

        public Criteria andBusinnameIsNull() {
            addCriterion("BusinName is null");
            return (Criteria) this;
        }

        public Criteria andBusinnameIsNotNull() {
            addCriterion("BusinName is not null");
            return (Criteria) this;
        }

        public Criteria andBusinnameEqualTo(String value) {
            addCriterion("BusinName =", value, "businname");
            return (Criteria) this;
        }

        public Criteria andBusinnameNotEqualTo(String value) {
            addCriterion("BusinName <>", value, "businname");
            return (Criteria) this;
        }

        public Criteria andBusinnameGreaterThan(String value) {
            addCriterion("BusinName >", value, "businname");
            return (Criteria) this;
        }

        public Criteria andBusinnameGreaterThanOrEqualTo(String value) {
            addCriterion("BusinName >=", value, "businname");
            return (Criteria) this;
        }

        public Criteria andBusinnameLessThan(String value) {
            addCriterion("BusinName <", value, "businname");
            return (Criteria) this;
        }

        public Criteria andBusinnameLessThanOrEqualTo(String value) {
            addCriterion("BusinName <=", value, "businname");
            return (Criteria) this;
        }

        public Criteria andBusinnameLike(String value) {
            addCriterion("BusinName like", value, "businname");
            return (Criteria) this;
        }

        public Criteria andBusinnameNotLike(String value) {
            addCriterion("BusinName not like", value, "businname");
            return (Criteria) this;
        }

        public Criteria andBusinnameIn(List<String> values) {
            addCriterion("BusinName in", values, "businname");
            return (Criteria) this;
        }

        public Criteria andBusinnameNotIn(List<String> values) {
            addCriterion("BusinName not in", values, "businname");
            return (Criteria) this;
        }

        public Criteria andBusinnameBetween(String value1, String value2) {
            addCriterion("BusinName between", value1, value2, "businname");
            return (Criteria) this;
        }

        public Criteria andBusinnameNotBetween(String value1, String value2) {
            addCriterion("BusinName not between", value1, value2, "businname");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("Password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("Password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("Password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("Password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("Password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("Password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("Password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("Password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("Password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("Password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("Password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("Password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("Password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("Password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPhonenumberIsNull() {
            addCriterion("Phonenumber is null");
            return (Criteria) this;
        }

        public Criteria andPhonenumberIsNotNull() {
            addCriterion("Phonenumber is not null");
            return (Criteria) this;
        }

        public Criteria andPhonenumberEqualTo(String value) {
            addCriterion("Phonenumber =", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberNotEqualTo(String value) {
            addCriterion("Phonenumber <>", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberGreaterThan(String value) {
            addCriterion("Phonenumber >", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberGreaterThanOrEqualTo(String value) {
            addCriterion("Phonenumber >=", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberLessThan(String value) {
            addCriterion("Phonenumber <", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberLessThanOrEqualTo(String value) {
            addCriterion("Phonenumber <=", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberLike(String value) {
            addCriterion("Phonenumber like", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberNotLike(String value) {
            addCriterion("Phonenumber not like", value, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberIn(List<String> values) {
            addCriterion("Phonenumber in", values, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberNotIn(List<String> values) {
            addCriterion("Phonenumber not in", values, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberBetween(String value1, String value2) {
            addCriterion("Phonenumber between", value1, value2, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andPhonenumberNotBetween(String value1, String value2) {
            addCriterion("Phonenumber not between", value1, value2, "phonenumber");
            return (Criteria) this;
        }

        public Criteria andApayidIsNull() {
            addCriterion("Apayid is null");
            return (Criteria) this;
        }

        public Criteria andApayidIsNotNull() {
            addCriterion("Apayid is not null");
            return (Criteria) this;
        }

        public Criteria andApayidEqualTo(String value) {
            addCriterion("Apayid =", value, "apayid");
            return (Criteria) this;
        }

        public Criteria andApayidNotEqualTo(String value) {
            addCriterion("Apayid <>", value, "apayid");
            return (Criteria) this;
        }

        public Criteria andApayidGreaterThan(String value) {
            addCriterion("Apayid >", value, "apayid");
            return (Criteria) this;
        }

        public Criteria andApayidGreaterThanOrEqualTo(String value) {
            addCriterion("Apayid >=", value, "apayid");
            return (Criteria) this;
        }

        public Criteria andApayidLessThan(String value) {
            addCriterion("Apayid <", value, "apayid");
            return (Criteria) this;
        }

        public Criteria andApayidLessThanOrEqualTo(String value) {
            addCriterion("Apayid <=", value, "apayid");
            return (Criteria) this;
        }

        public Criteria andApayidLike(String value) {
            addCriterion("Apayid like", value, "apayid");
            return (Criteria) this;
        }

        public Criteria andApayidNotLike(String value) {
            addCriterion("Apayid not like", value, "apayid");
            return (Criteria) this;
        }

        public Criteria andApayidIn(List<String> values) {
            addCriterion("Apayid in", values, "apayid");
            return (Criteria) this;
        }

        public Criteria andApayidNotIn(List<String> values) {
            addCriterion("Apayid not in", values, "apayid");
            return (Criteria) this;
        }

        public Criteria andApayidBetween(String value1, String value2) {
            addCriterion("Apayid between", value1, value2, "apayid");
            return (Criteria) this;
        }

        public Criteria andApayidNotBetween(String value1, String value2) {
            addCriterion("Apayid not between", value1, value2, "apayid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dwh_business
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 21 20:51:44 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dwh_business
     *
     * @mbg.generated Tue Apr 21 20:51:44 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}