package com.dwh.payweb.entity;

public class Goods_proKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_goods_pro.Gid
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    private String gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_goods_pro.proid
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    private String proid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_goods_pro.Gid
     *
     * @return the value of dwh_goods_pro.Gid
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_goods_pro.Gid
     *
     * @param gid the value for dwh_goods_pro.Gid
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_goods_pro.proid
     *
     * @return the value of dwh_goods_pro.proid
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public String getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_goods_pro.proid
     *
     * @param proid the value for dwh_goods_pro.proid
     *
     * @mbg.generated Tue Nov 05 22:44:27 CST 2019
     */
    public void setProid(String proid) {
        this.proid = proid == null ? null : proid.trim();
    }
}