package com.dwh.payweb.entity;

import java.util.Date;

public class Trade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_trade.tradeid
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    private String tradeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_trade.m_price
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    private String mPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_trade.gids
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    private String gids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_trade.versions
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    private String versions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_trade.paytime
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_trade.numbers
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    private String numbers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_trade.status
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_trade.dprices
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    private String dprices;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwh_trade.aprices
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    private String aprices;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_trade.tradeid
     *
     * @return the value of dwh_trade.tradeid
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public String getTradeid() {
        return tradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_trade.tradeid
     *
     * @param tradeid the value for dwh_trade.tradeid
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public void setTradeid(String tradeid) {
        this.tradeid = tradeid == null ? null : tradeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_trade.m_price
     *
     * @return the value of dwh_trade.m_price
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public String getmPrice() {
        return mPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_trade.m_price
     *
     * @param mPrice the value for dwh_trade.m_price
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public void setmPrice(String mPrice) {
        this.mPrice = mPrice == null ? null : mPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_trade.gids
     *
     * @return the value of dwh_trade.gids
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public String getGids() {
        return gids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_trade.gids
     *
     * @param gids the value for dwh_trade.gids
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public void setGids(String gids) {
        this.gids = gids == null ? null : gids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_trade.versions
     *
     * @return the value of dwh_trade.versions
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public String getVersions() {
        return versions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_trade.versions
     *
     * @param versions the value for dwh_trade.versions
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public void setVersions(String versions) {
        this.versions = versions == null ? null : versions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_trade.paytime
     *
     * @return the value of dwh_trade.paytime
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_trade.paytime
     *
     * @param paytime the value for dwh_trade.paytime
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_trade.numbers
     *
     * @return the value of dwh_trade.numbers
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public String getNumbers() {
        return numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_trade.numbers
     *
     * @param numbers the value for dwh_trade.numbers
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public void setNumbers(String numbers) {
        this.numbers = numbers == null ? null : numbers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_trade.status
     *
     * @return the value of dwh_trade.status
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_trade.status
     *
     * @param status the value for dwh_trade.status
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_trade.dprices
     *
     * @return the value of dwh_trade.dprices
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public String getDprices() {
        return dprices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_trade.dprices
     *
     * @param dprices the value for dwh_trade.dprices
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public void setDprices(String dprices) {
        this.dprices = dprices == null ? null : dprices.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwh_trade.aprices
     *
     * @return the value of dwh_trade.aprices
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public String getAprices() {
        return aprices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwh_trade.aprices
     *
     * @param aprices the value for dwh_trade.aprices
     *
     * @mbg.generated Sat Nov 09 15:31:04 CST 2019
     */
    public void setAprices(String aprices) {
        this.aprices = aprices == null ? null : aprices.trim();
    }
}